apiVersion: v1
kind: Service
metadata:
  name: todolist-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: Todos-nodejs-
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30000